name = "httpi-cfworkers-example"
main = "./src/server.ts"
compatibility_date = "2024-06-08"
compatibility_flags = [ "nodejs_compat" ]

[dev]
port = 3000

[vars]
# DISCORD_CLIENT_ID = ""
# DISCORD_PUBLIC_KEY = ""
# DISCORD_TOKEN = ""
